### ISSUE TITLE
Final points distribution screen

### ISSUE THREAD

**Issue by TurboUrbo** [decentfund/kyodo#101]
results of the period (points earned)
need to sign the trans / approving points allocation within a period
time till the period's allocation

**Comment by romochka** [comment]
<img width="963" alt="token-alloc" src="https://user-images.githubusercontent.com/25977424/45637502-50a98780-bab3-11e8-9a7d-f16a6380dc0b.png">

**Comment by TurboUrbo** [comment]
Beautiful! <3

**Comment by TurboUrbo** [comment]
The button is lovely!
