### ISSUE TITLE
Fix navigation

### ISSUE THREAD

**Issue by TurboUrbo** [decentfund/kyodo#115]
Here is the site map  / We need to fix navigation
![](https://i.imgur.com/APZQnUL.png)

**Comment by romochka** [comment]
Allocation and Points Allocation - the difference? what is Allocation exactly?

**Comment by TurboUrbo** [comment]
Points allocation https://github.com/decentfund/kyodo/issues/101
Allocation - Token distribution  https://github.com/decentfund/kyodo/issues/79#issuecomment-416656445

**Comment by romochka** [comment]
![nav00](https://user-images.githubusercontent.com/25977424/46167332-34b99900-c29e-11e8-8bbc-14225a5cba2a.png)
![nav01](https://user-images.githubusercontent.com/25977424/46167340-384d2000-c29e-11e8-80c0-3f2a112f870f.png)
![nav02](https://user-images.githubusercontent.com/25977424/46167342-3aaf7a00-c29e-11e8-81e4-a3979a7f8eb7.png)
![nav03](https://user-images.githubusercontent.com/25977424/46167350-3e430100-c29e-11e8-8400-761ed1a2816c.png)

**Comment by romochka** [comment]
I was thinking, generally speaking, we should have top level menu of:
-fund performance (STATS),
-everything member-related (MEMBERS),
-fund management (GOVERNANCE or SETTINGS),
-actions, what is happening now, completing tasks, giveaway tips (POINTS or TASKS or maybe call it ACTION)

**Comment by igorline** [comment]
@romochka we might need some kind of notification system. Can we somehow highlight menu to communicate updates on some pages?
New period start, new tips, new voting as examples

**Comment by romochka** [comment]
i think this could be ummm noticeable
<img width="1000" alt="notification1" src="https://user-images.githubusercontent.com/25977424/46247897-ca7a3300-c41a-11e8-854d-788da44a7c0a.png">
<img width="1000" alt="notification2" src="https://user-images.githubusercontent.com/25977424/46247898-ca7a3300-c41a-11e8-8ebb-0d6075a00452.png">
<img width="1000" alt="notification3" src="https://user-images.githubusercontent.com/25977424/46247899-ca7a3300-c41a-11e8-8682-9385947c3476.png">
<img width="1000" alt="notification4" src="https://user-images.githubusercontent.com/25977424/46247900-cb12c980-c41a-11e8-9b5c-121b4243aacb.png">

**Comment by TurboUrbo** [comment]
so coool!

**Comment by igorline** [comment]
I'm closing this issue in favor of #144
