### ISSUE TITLE
Favicon for kyodo page

### ISSUE THREAD

**Issue by igorline** [decentfund/kyodo#130]

**Comment by romochka** [comment]
[favicon.zip](https://github.com/decentfund/kyodo/files/2420545/favicon.zip)

**Comment by romochka** [comment]
![image](https://user-images.githubusercontent.com/25977424/46092840-6f4c0480-c1be-11e8-8aaf-17fb1f99b1b5.png)

**Comment by romochka** [comment]
[favicon.zip](https://github.com/decentfund/kyodo/files/2437660/favicon.zip)
plz replace the favicon with this un poco updated

**Comment by igorline** [comment]
![image](https://user-images.githubusercontent.com/1465430/46889110-e7732500-ce62-11e8-81b1-ab4450814406.png)

Updated
