### ISSUE TITLE
DF token ownership percentage displays incorrectly

### ISSUE THREAD

**Issue by pasha0x** [decentfund/kyodo#165]
In "Members" tab of dapp DF token ownership percentage displays incorrectly.
Steps to reproduce:
log in Metamask
go http://kyodo.decent.fund
go Members
go Members one more time in new browser tab
![kyodo111](https://user-images.githubusercontent.com/44088175/46865378-043d3780-ce26-11e8-9b92-2b769aee112a.jpg)

**Comment by igorline** [comment]
Hey! Will be fixed today! :) Thanks for posting

**Comment by pasha0x** [comment]
Great! :)
