### ISSUE TITLE
Humanize bot phrases

### ISSUE THREAD

**Issue by pasha0x** [decentfund/kyodo#173]
Change bot vocabulary to more human alike.
"You have 0 points. But don't worry! You can earn them by making contributions other people find useful. 
Or just by making me laugh."
![photo_2018-10-13_00-06-59](https://user-images.githubusercontent.com/44088175/46894143-1e096980-ce7c-11e8-917d-2f0c5f9f5011.jpg)

**Comment by igorline** [comment]
@pasha0x, please, verify the fix

Though it might be related to #133 and another fix will follow up tomorrow

**Comment by pasha0x** [comment]
Now when I'm trying to dish bot saying
"Uh-oh! Something went wrong! Please contact admin from the chat and submit a ticket with details in the repo http://github.com/decentfund/kyodo"

**Comment by igorline** [comment]
@pasha0x, this is expected action. I'm finishing database migrations and fixes for that!
Will be fixed today

**Comment by igorline** [comment]
@pasha0x, please, verify issue is fixed

**Comment by pasha0x** [comment]
![screenshot_20181027-145931_riotim](https://user-images.githubusercontent.com/44088175/47603752-13f97600-d9f9-11e8-88c4-9248914b69d3.jpg)

Success!
