### ISSUE TITLE
Fix content of help bot command

### ISSUE THREAD

**Issue by igorline** [decentfund/kyodo#210]
`!help` command should send back more relevant information with domains description.

@TurboUrbo, can you help with the full message that bot should be responding?

**Comment by TurboUrbo** [comment]
Should i use this command as a basis?
!dish 30 SOCIAL points to @alina_loseva for drawing brilliant 💎 sketches on QV

**Comment by igorline** [comment]
Well, when you write `!help` bot should *help* you :) That's the basis.
Any wrong command should point to ask bot for` !help`

**Comment by TurboUrbo** [comment]
!dish
To express your level of impression send evaluation points to a person you are impressed by:
!dish [#of points] [type of points] points to [handle] for [reason]
Example: !dish 50 BUIDL points to @igorline for crazy coding ★★★★★
To know your points balance use !balance command

**Comment by TurboUrbo** [comment]
!balance 
if positive: ♥‿♥ wow you have 1000 points to tip / 20 days till the end of Crypto Middle ages period 
if zero: ＾･ｪ･＾you have [ ⚫ ] points. No worries, it's temporarily! Tip others and get tipped by doing smth cool or nerdy or beautiful or readable ;) 
if newcomer (could we know such a data?): (✿◠‿◠) hello! you have [ ⚫ ] points. Please wait a bit for the next period to get your points and tip / 20 days till the end of Crypto Middle ages period

**Comment by igorline** [comment]
:+1:
