### ISSUE TITLE
Display incorrect network connection

### ISSUE THREAD

**Issue by igorline** [decentfund/kyodo#61]

**Comment by romochka** [comment]
<img width="1000" alt="metamask-warning" src="https://user-images.githubusercontent.com/25977424/47602633-4cde1e80-d9ea-11e8-95e9-a61c694192dc.png">

**Comment by igorline** [comment]
@palevoo, ready for buidling :)

https://www.figma.com/file/BVOa95pI3f9OVc1N0EQXXvPY/kyodo

**Comment by igorline** [comment]
@jsidorenko maybe you can take this one
