### ISSUE TITLE
Multisig wallet balance screen

### ISSUE THREAD

**Issue by igorline** [decentfund/kyodo#63]
Currently fund capitalization and token price information is very uninformative. It would be useful to have separate screen displaying real-time fund portfolio balance with tokens and their balances.

I'm attaching aragon ui section representation.

![image](https://user-images.githubusercontent.com/1465430/44036515-3c194d30-9f12-11e8-888a-6f216f144a03.png)

**Comment by igorline** [comment]
Actually I think we will need to have something wore complex.
We need to display amount of specific tokens we hold, share of tokens, price of DF token and fund cap in time using some chart.

Good examples:
https://hodl50.fund/
https://www.iconomi.net/dashboard/daa/CCC

**Comment by romochka** [comment]
![fund-stats](https://user-images.githubusercontent.com/25977424/44992943-76a63680-afa1-11e8-8c0f-c9c65cc09158.png)

**Comment by igorline** [comment]
@romochka coooool! Can we also display somehow (maybe on hover) share percentage of specific token in portfolio?

**Comment by romochka** [comment]
![fund-stats-w-percentage](https://user-images.githubusercontent.com/25977424/45001634-585b2d80-afd7-11e8-8c64-5f784821c6e4.png)

yep

**Comment by igorline** [comment]
@romochka, on hover we show EUR icon and change percentage bar and type color, right?
