### ISSUE TITLE
Members screen fixes

### ISSUE THREAD

**Issue by TurboUrbo** [decentfund/kyodo#77]
Add the third column "Balance" to the list of members. The balance of DF token (%) each member will be placed in front of ETH address
"No nickname" solution - random icons?
Number of  members

**Comment by igorline** [comment]
@TurboUrbo for unspecified nickname we use 'member known as'

**Comment by romochka** [comment]
![members](https://user-images.githubusercontent.com/25977424/44995417-9e9a9780-afab-11e8-9820-0a94cae888b1.png)

we should get rid of that weird three dots; if there's not enough horizontal space, then better would be the smaller font size, like 16px instead of 18px
