### ISSUE TITLE
Control to allow transfer of DF tokens

### ISSUE THREAD

**Issue by TurboUrbo** [decentfund/kyodo#78]

**Comment by igorline** [comment]
@romochka on the screen where you are assigning your riot ID we need some control to allow tokens transfer

**Comment by igorline** [comment]
![image](https://user-images.githubusercontent.com/1465430/44510362-cb4dd580-a6b4-11e8-8432-30f8549349c7.png)

**Comment by romochka** [comment]
![deny](https://user-images.githubusercontent.com/25977424/44515904-5b4b4980-a6cc-11e8-9941-3c98af407018.png)
![allow](https://user-images.githubusercontent.com/25977424/44515913-5eded080-a6cc-11e8-93f6-493f29c70ecf.png)

**Comment by igorline** [comment]
Closing this issue till we might need to have access to user tokens.
Might be reopened in #174
